### ISSUE TITLE
Unify all docs on developer.tbd.website to respect one dependency

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#532]
Introduce a Bill of Materials. 

This will give us a single place to update, for instance, a Web5 or SSI dependency. All downstream efforts with the Web5 dependency: TODO App Guide, TODO app starter template, TODO app finished example, Quickstart, Quickstart index.js, Quickstart front-end widget - respect and use that one declared dependency.  This gives us one place to update across the entire docs suite - no more cascading updates in several places and issuing new releases across different repos.

@dayhaysoos to dig in and provide an RFC for stakeholder review.

**Comment by dayhaysoos** [comment]
**Proposal: Centralization of Examples in developer.tbd.website Repo**


First of all, I just want to say that this is one step of many towards making a smoother process when it comes to going from release to docs being updated.

I suggest we add a dedicated `examples` folder in the `developer.tbd.website` repository to consolidate the separate repositories we currently maintain for examples.

Currently, the following examples are maintained in separate repositories:

- TODO App Guide
- TODO App starter template
- TODO app finished examples
- Quickstart frontend Widget

Managing these separate repositories has been cumbersome and lead to inconsistencies and tracking issues. I think a good first step would be to move all these repos under an `examples` folder. By making this folder, it would help with:

- **Improved Efficiency**: Having a centralized location for all examples will streamline our update process and eliminate the need to switch between repositories.
- **Ease of Tracking**: We can track changes and updates across all examples more effectively when they are in one location.
- **Consistency**: It will help to ensure that changes made are consistent across all examples.

I also propose that we should make it a requirement that each example should work "out of the box". If the example is in an index.html, we should be able to see it working from copying/pasting into a local html file, for example This would help avoid any path or dependency issues and improve the experience for developers who are trying out or learning from our examples.

The scope of this step is pretty small, but I would love to talk about expanding from here. Here are some things that we should talk about:

- Reactifying the Quickstart to make it easier to reason about and edit
- Ways to synchronize between examples and tutorials (are there certain tools we can use to handle this, ways we can template it?)
- Editing the examples/tutorials so they are 1:1 copies of each other (basically, the same exact code being written in the example is also being used for the tutorial, I noticed we had to refactor things to fit the appropriate context)


I'll leave it here for now, feel free to share any thoughts or concerns around this task.

**Comment by bobbilee19** [comment]
1000% yes. Thank you for writing this all out. And apologies I didn't see it right away, so sorry.

So yes this would make our lives so much simpler. 

So I see it that these need to be moved into `examples`:
1. Incubating Labs TODO app 
2. Quickstart Frontend Widget (where is this? I haven't been updating this)
3. Everything in `web5-tutorials` repo needs to be squashed and moved

**Comment by ALRubinger** [comment]
Sounds appropriate @dayhaysoos - and will unlock a lot for us in subsequent stages reducing maintenance burden.

Questions:

* Where do we put the single dependency declaration for Web5, for SSI, etc? How do the things under the `examples` directory you propose honor that single declaration?
* How are you thinking about this; is the `example` folder you propose something that's under the existing root of `developer.tbd.website`? Or is it a move into a monorepo-like approach like you'd mentioned a couple of times prior?
* Is `examples` a term that covers the full suite of things we're looking to align under one roof? We existing assets are: 1) completed examples, showing what the expected "done" state is if the user follows a guide/tutorial 2) The starting point "template" for devs to pull and build atop 3) Playgrounds intended to be deployed, or followed as examples
* And also to be included there - the QuickStart `index.js`, yes? That's the "completed example" if the QuickStart is done right, and what we should be pulling from to assemble the code snippits in the QuickStart.

**Comment by angiejones** [comment]
I have hesitation about this part:

> Editing the examples/tutorials so they are 1:1 copies of each other (basically, the same exact code being written in the example is also being used for the tutorial, I noticed we had to refactor things to fit the appropriate context)

In most cases, it's healthy to have the examples vary to show the flexibility of the system. There's so many optional parameters and combinations of calls. We don't want to just show one flavor. With proper context, we're showing developers how to customize their code for specific use cases

**Comment by angiejones** [comment]
@dayhaysoos, looking for more info on how the dependency will be set up and incorporated in the examples

**Comment by dayhaysoos** [comment]
Hey @angiejones !!

 **About your hesitation:**

I agree that it's healthy to show variations of how to use something, however, I also think it can go both ways, where seeing more than one example done in different ways can be really confusing at the same time. I think this might be something that comes down to how it's executed.

I think we can come to a happy medium where we mention that we offer optional params and configurations and link off to those specifically in case they're interested in that.

**Relocating the TODO App**

This is a good question, I sort of see 2 approaches here.

Stripe has a repo dedicated to examples, snippets, demos. I think the key takeaway here is that everything is downloadable and runnable out the box, which could be really nice to have: 

https://github.com/stripe-samples

I think they're scoped down to really small features, like just doing a simple payment for a specific tech stack or something. 

Another approach is how Vercel does it. They have a massive directory full of examples:

https://github.com/vercel/vercel/tree/main/examples

I personally like this because it's all under one place. When I need to see how something is set up or implemented I don't have to search for a specific repo. You can explore this directory to see if what you need is in here. As far as how people could run it locally, we'd have to defer to external tooling for that but we can go over that soon.


**Example Dependency concern**
cc @ALRubinger 

I think the best move would be to switch to a monorepo and use `pnpm` instead of npm. `pnpm` is way more efficient at managing dependencies in a performative way, and all versions are scoped to the specific examples. You won't end up with colliding dependency versions between examples like you possibly could with npm. It's also easier to test these examples locally with workspaces before we ship.

I use `pnpm`

With use-shopping-cart:

Config:
https://github.com/dayhaysoos/use-shopping-cart/blob/master/pnpm-workspace.yaml

The scripts in the `package.json` are reflective on `pnpm` as well:

https://github.com/dayhaysoos/use-shopping-cart/blob/master/package.json#L2

Switching to `pnpm` won't feel like such a huge change, it'll bring us a step closer to feeling like we have more control over more things under one repo, though. Would love to know y'all thoughts!

**Comment by ALRubinger** [comment]
On its bones, sounds pretty great to me.

So the new structure you're envisioning is:

```
developer.tbd.website (repo)
- site/ (contains a full lift of the existing repo; the Docusaurus site)
- examples/ (or another name, to contain contents of tutorial starter templates, finished examples, playgrounds, etc. Each app in here has its own README and build script, honoring the top-line dependencies declared in the root folder)
- package.json (contains top-level dependencies respected by both the site and all "examples"
```

...?

If so, TL;DR of my thoughts:

* I *do* think it makes sense to unify all `examples` as you've defined them into a monorepo, with top-level dependencies (BOM)
* I may have evolved my opinion - I *don't* feel it makes natural sense to couple the `examples` monorepo with the dev site.

I think the natural dependency tree looks like:

`Web5` | `SSI` upstream projects > `examples` monorepo > Dev Site

In that way the examples could be uniformly versioned together. We could cut a release for that monorepo, and the Dev Site could declare a single dependency on that monorepo's tag to build the published docs.

Either way, sounds to me like @dayhaysoos has laid out a great proposal and unified our thinking; I'm eager to bring the opinions into a room on `tbd-stage` and drive to a conclusion by end of week so we can take action and start unifying things to ease particularly @bobbilee19's maintenance burden and that of the Web5 team.

**Comment by dayhaysoos** [comment]
For me, `examples` are part of our docs. We will be referring to these examples from our docs site and that's the main reason why I'm proposing we put it all under one monorepo.

I would definitely like to learn more about examples being uniformly versioned together. While it sounds nice to have examples that are also versioned with the docs, I can't help but feel like examples should always reflect the most recent version while the docs themselves are versioned in a way that they can be referred to for previous releases.

With that being said, I bet we can figure out a way to version the examples if we need to.
