### ISSUE TITLE
Add info on Web5 ChatGPT Plugin

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#563]
@michaelneale has had the [web5 ChatGPT plugin](https://github.com/TBD54566975/web5-chatgpt-plugin/tree/main/content) approved, and it should be in the plugin store soon. When it is, let's be sure to link to it and maybe provide instructions on how to activate the plugin and provide examples of what it can do (Mic has great examples in the plugin repo linked above)

**Comment by michaelneale** [comment]
Some guidelines I got from OpenAI when advertising this: 


Hey there,

We’re excited to share that your ChatGPT plugin has been approved. Your plugin will be made available in the store today. Please read this note in its entirety to avoid any future confusion.

Please note that ChatGPT plugins are still in Beta and changes may be made to our store appearance, guidelines, or review process. Plugins are currently available to all ChatGPT plus users. If you want to join our invite only developer space for those with plugins in the plugin store, please join our [developer forum](https://community.openai.com/invites/tkWo2dNX3o). If you are already a part of the developer forum, please [request access](https://community.openai.com/g/Plugin_Store_Devs) to the group and make it clear which plugin you work on.

To ensure any news about your plugin is communicated accurately, we ask that you follow the following guidelines:

If you plan to make announcements, please review our [Brand Guidelines](https://openai.com/brand). If your announcement, blog, or other communications go beyond the guidelines, or if you have any questions, please reach out to OpenAI’s Partner Communications team at [partnercomms@openai.com](mailto:partnercomms@openai.com). You’re welcome to use this language to set expectations with users appropriately: “ChatGPT plugins are rolling out gradually.” Since plugins are in alpha, please let your users know changes to the plugins user interface or performance (i.e. latency) may occur.
We speak to reporters all the time who are interested in new use cases, so we’d love to be kept up to date about your plans. Please reach out to [partnercomms@openai.com](mailto:partnercomms@openai.com)
When referring to plugins, please use the term “plugin” rather than other names. Your company or product name should appear first, followed by OpenAI or the model. Please do not lead with OpenAI or the OpenAI model name. For example: [Company Name] plugin for ChatGPT or [Company Name] ChatGPT plugin are acceptable.
The words partnership or collaboration should not be used to communicate your company’s relationship with OpenAI. Please refer to the [Brand Guidelines](https://openai.com/brand) for examples.
Please do not speak on behalf of OpenAI or discuss details of the plugin approval process publicly. If you participate in media interviews, we ask that you give OpenAI a heads-up prior to participation and direct questions about OpenAI to [press@openai.com](mailto:press@openai.com).

**Comment by michaelneale** [comment]
@angiejones ok I have updated the plugin with a lot more docs, examples, including your new protocols guide, and the api docs, and it seems to work even better (I am basing it off the website - but there is a rich example of dinger in there, as the documented stuff works better with AI as it does with humans, no surprise there! so kudos for doing that and we find another use). 

Some more examples I have tried: 

![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/ba831ebc-c78c-48c5-9d6e-07eb9ff28846)


![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/686007e8-07a5-4c47-951c-75c02154cbf2)

It can also cite things: 

![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/3bcfb3ba-d36f-4a39-ac37-7089449453b8)

And it is now in the plugin store, so if you have ChatGPT with plugin access, you can just install it and use it freely: 

![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/cdd83b73-0632-4b86-8ffd-a6dd2b42b43c)

**Comment by angiejones** [comment]
love it @michaelneale! on it
