### ISSUE TITLE
Browser tests: dinger-completed

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#993]

**Comment by samejima-san** [comment]
can i take a stab at this?

**Comment by blackgirlbytes** [comment]
@samejima-san hey, I'm mad happy that you want to contribute to this repo. I would say I probably should keep this one because:
- it needs to go out for our next release, 
- I wrote the app that I need to make tests for..and it's a little quirky
-  and we discussed the approach internally. 

However, I did create an issue the other day that you can pick up: https://github.com/TBD54566975/developer.tbd.website/issues/1005

**Comment by samejima-san** [comment]
@blackgirlbytes i'm on it!
